pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-nginx:latest ./01-CI-CD-k8s-project'
            }
        }

        stage('Run Container Test') {
            steps {
                sh 'docker run -d --name test-nginx -p 8080:80 my-nginx:latest'
            }
        }

        stage('Test') {
            steps {
                sh 'curl http://localhost:8080'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker stop test-nginx || true'
                sh 'docker rm test-nginx || true'
            }
        }
    }
}
