apiVersion: v1
kind: Service
metadata:
  name: automation-with-cicd-service
spec:
  selector:
    app: automation-with-cicd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

